### ISSUE TITLE
divider not shown

### ISSUE THREAD

**Issue by rkarlsba** [larsch/lasercut-box-openscad#3]
I tried to make a simple model with two deviders vertically, and for some reason one of them doesn't show up unless I set deviders=2.00000001 or something. Library was just checked out from github and Openscad is version 2015.03-3. Please see attached screenshots.

roy
![skjermbilde 2017-08-13 kl 14 31 18](https://user-images.githubusercontent.com/4253147/29249682-b5cd0534-8034-11e7-8749-2aae33169204.png)
![skjermbilde 2017-08-13 kl 14 31 26](https://user-images.githubusercontent.com/4253147/29249684-b8691f76-8034-11e7-813d-16d85cae1c01.png)

**Comment by larsch** [comment]
Fixed. Thanks for reporting.

![image](https://user-images.githubusercontent.com/15712/29250657-a7216edc-8046-11e7-9057-64ded9e11c21.png)
